config/routes.rb
Rails.application.routes.draw do
  resources :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  validates :title, presence: true
  validates :author, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    render json: @books
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      redirect_to @book
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :author)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categorys = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      redirect_to @category
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to '/categories'
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.haml
%main
  .errors
    - @book.errors.full_messages.each do |error|
      .error= error

  = form_for @book do |f|
    .input
      = f.label :title
      = f.text_field :title
    .input
      = f.label :author
      = f.text_field :author
    = f.submit

app/views/books/edit.html.haml
%header
  = link_to "account_balance", "/", class: "material-icons"
  .title
    %h1 Rails Library
    %span -
    %h2 Edit Book

= render "form"

app/views/books/index.html.haml
%header
  = link_to "account_balance", "/", class: "material-icons"
  .title
    %h1 Rails Library
    %span -
    %h2 Books

%main
  = link_to "Add New Book", new_book_path

  %table
    %tr
      %th Title
      %th Author
      %th Show
      %th Edit
      %th Delete
    - @books.each do |book|
      %tr
        %td= book.title
        %td= book.author
        %td= link_to "show", book_path(book)
        %td= link_to "edit", edit_book_path(book)
        %td= link_to "delete", book_path(book), method: :delete

app/views/books/new.html.haml
%header
  = link_to "account_balance", "/", class: "material-icons"
  .title
    %h1 Rails Library
    %span -
    %h2 New Book

= render "form"

app/views/books/show.html.haml
%header
  = link_to "account_balance", "/", class: "material-icons"
  .title
    %h1 Rails Library
    %span -
    %h2 Book


%main

  %div
    %span Title:
    %strong= @book.title

  %div
    %span Author:
    %strong= @book.author

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails Library</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= yield %>

</body>
</html>